In [12]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, BatchNormalization, Conv2D, Dense, Flatten, MaxPooling2D
from tensorflow.keras.utils import to_categorical
import pickle
import numpy as np

In [13]:
(_, _), (X_test, y_test) = cifar10.load_data()

y_test = to_categorical(y_test, num_classes = 10)

In [14]:
with open('saved_images_with_labels11.pkl', 'rb') as f:
    loaded_data = pickle.load(f)

# Восстанавливаем тензоры из numpy
x_train1 = [img for img in loaded_data['images']]
x_train1 = np.squeeze(x_train1, axis=1)
y_train1 = loaded_data['labels']  # список лейблов
y_train1 = tf.keras.utils.to_categorical(y_train1, 10)

In [20]:
with open('saved_images_with_labels22.pkl', 'rb') as f:
    loaded_data = pickle.load(f)

# Восстанавливаем тензоры из numpy
x_train2 = [img for img in loaded_data['images']]
x_train2 = np.squeeze(x_train2, axis=1)
y_train2 = loaded_data['labels']  # список лейблов
y_train2 = tf.keras.utils.to_categorical(y_train2, 10)

In [21]:
print("Shape of x_train1:", np.array(x_train1).shape)
print("Shape of y_train1:", np.array(y_train1).shape)
print("Shape of x_train2:", np.array(x_train2).shape)
print("Shape of y_train2:", np.array(y_train2).shape)
print(type(x_train1))
print(type(x_train2))

Shape of x_train1: (25000, 32, 32, 3)
Shape of y_train1: (25000, 10)
Shape of x_train2: (25000, 32, 32, 3)
Shape of y_train2: (25000, 10)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [22]:
x_train = np.concatenate((x_train1, x_train2))
y_train = np.concatenate((y_train1, y_train2))

In [23]:
print(x_train[0], y_train[0])

[[[0.60144943 0.62705994 0.64409125]
  [0.60612696 0.63376963 0.65537566]
  [0.6131762  0.6391788  0.6577437 ]
  ...
  [0.605248   0.63508856 0.65222645]
  [0.6061369  0.63702273 0.6561485 ]
  [0.59092826 0.61969906 0.63759845]]

 [[0.606669   0.631468   0.6546343 ]
  [0.6004275  0.6250537  0.65014434]
  [0.61200166 0.63602626 0.6577935 ]
  ...
  [0.6022604  0.63247234 0.6519245 ]
  [0.60536116 0.6347779  0.6555398 ]
  [0.5966766  0.6286795  0.6482785 ]]

 [[0.6062583  0.63050675 0.6503364 ]
  [0.5988378  0.6237264  0.6472945 ]
  [0.607926   0.6320114  0.65514123]
  ...
  [0.60088104 0.63044286 0.6499933 ]
  [0.6025504  0.6340153  0.65397143]
  [0.5970278  0.6295282  0.646966  ]]

 ...

 [[0.5440607  0.5475953  0.5232548 ]
  [0.5403011  0.5428536  0.52077496]
  [0.54331934 0.5484569  0.5295828 ]
  ...
  [0.5411851  0.5491042  0.53392655]
  [0.53914523 0.54726464 0.531924  ]
  [0.53205824 0.5425022  0.5256012 ]]

 [[0.54192567 0.54408926 0.52155703]
  [0.538756   0.5397659  0.51993126]


In [24]:
indices = np.arange(len(x_train))
np.random.shuffle(indices)

# Применяем одинаковую перестановку к данным и меткам
x_train = x_train[indices]
y_train = y_train[indices]

In [25]:
print(x_train[0], y_train[0])

[[[0.5821462  0.5905529  0.5643691 ]
  [0.5876964  0.59609586 0.5700264 ]
  [0.5905287  0.5985027  0.5737368 ]
  ...
  [0.5888993  0.5946159  0.571522  ]
  [0.5902075  0.59837204 0.57798594]
  [0.5758707  0.58624226 0.56827575]]

 [[0.58257365 0.589069   0.5639596 ]
  [0.5762667  0.583596   0.55865276]
  [0.5806981  0.5890375  0.5657742 ]
  ...
  [0.57849085 0.58342946 0.56022334]
  [0.5824784  0.58899873 0.5663341 ]
  [0.578363   0.58762664 0.5643624 ]]

 [[0.57680064 0.5831806  0.55686605]
  [0.569488   0.5770001  0.5519359 ]
  [0.57296896 0.5815743  0.55892634]
  ...
  [0.56872237 0.57424986 0.5518112 ]
  [0.5745171  0.5803019  0.55595183]
  [0.5749121  0.58236605 0.55616134]]

 ...

 [[0.50184053 0.4956556  0.4600541 ]
  [0.48667914 0.47803336 0.44401145]
  [0.4812698  0.4730473  0.4425063 ]
  ...
  [0.48045632 0.47241464 0.42807347]
  [0.48787406 0.48108482 0.4374667 ]
  [0.49450028 0.49045908 0.44573957]]

 [[0.50614077 0.5002353  0.46544975]
  [0.49261138 0.48430073 0.45040047]


In [26]:
print("Shape of x_train:", np.array(x_train).shape)
print("Shape of y_train:", np.array(y_train).shape)

Shape of x_train: (50000, 32, 32, 3)
Shape of y_train: (50000, 10)


In [28]:
model = Sequential()
model.add(Conv2D(64,(3,3),activation='relu', padding='same', input_shape=(32,32,3)))
model.add(BatchNormalization())
model.add(Conv2D(64, (3,3), activation = 'relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))

model.add(Conv2D(128, (3,3), activation = 'relu', padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(128, (3,3), activation = 'relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))

model.add(Conv2D(256, (3,3), activation = 'relu', padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(256, (3,3), activation = 'relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))


model.add(Conv2D(512, (3,3), activation = 'relu', padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(512, (3,3), activation = 'relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))

model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(10, activation = 'softmax'))

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_16 (Conv2D)              │ (None, 32, 32, 64)     │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_18          │ (None, 32, 32, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_17 (Conv2D)              │ (None, 32, 32, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_19          │ (None, 32, 32, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_8 (MaxPooling2D)  │ (None, 16, 16, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 16, 16, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_18 (Conv2D)              │ (None, 16, 16, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_20          │ (None, 16, 16, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_19 (Conv2D)              │ (None, 16, 16, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_21          │ (None, 16, 16, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_9 (MaxPooling2D)  │ (None, 8, 8, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ (None, 8, 8, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_20 (Conv2D)              │ (None, 8, 8, 256)      │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_22          │ (None, 8, 8, 256)      │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_21 (Conv2D)              │ (None, 8, 8, 256)      │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_23          │ (None, 8, 8, 256)      │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_10 (MaxPooling2D) │ (None, 4, 4, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_12 (Dropout)            │ (None, 4, 4, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_22 (Conv2D)              │ (None, 4, 4, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_24          │ (None, 4, 4, 512)      │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_23 (Conv2D)              │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼─────────────

 Total params: 4,957,130 (18.91 MB)

 Trainable params: 4,953,034 (18.89 MB)

 Non-trainable params: 4,096 (16.00 KB)

In [29]:
model.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [30]:
model.fit(x_train, y_train, batch_size = 32, epochs = 10, verbose = 1)

Epoch 1/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 52s 28ms/step - accuracy: 0.7344 - loss: 0.7353
Epoch 2/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 40s 26ms/step - accuracy: 0.8307 - loss: 0.4744
Epoch 3/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 52s 33ms/step - accuracy: 0.8372 - loss: 0.4469
Epoch 4/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 54s 35ms/step - accuracy: 0.8438 - loss: 0.4253
Epoch 5/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 54s 35ms/step - accuracy: 0.8510 - loss: 0.4131
Epoch 6/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 56s 36ms/step - accuracy: 0.8510 - loss: 0.4097
Epoch 7/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 63s 40ms/step - accuracy: 0.8550 - loss: 0.3977
Epoch 8/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 67s 43ms/step - accuracy: 0.8564 - loss: 0.3903
Epoch 9/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 67s 43ms/step - accuracy: 0.8589 - loss: 0.3848
Epoch 10/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 67s 43ms/step - accuracy: 0.8590 - loss: 0.3871


In [31]:
score = model.evaluate(X_test, y_test)
print('Accuracy:', score[1])

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.1187 - loss: 5330.8330
Accuracy: 0.11959999799728394
